---
title: "data_cleaning"
author: "Logan Williams"
date: "2/24/2020"
output: html_document
params:
  
  #Change Every month
  month: March
  pastyear: 2019
  year: 2020 
                 
  # Compiles Year to Date Dataset for this year | Leave at January 1st 2020
  ytd: "2020-01-01" 
               
  # First day of current month | Change this each month
  date: "2020-01-01"   
  
  # First day of next month | Change this each month
  enddate: "2020-02-01"
           
  #Leave at January 1st of last year | Compiles Year to Date Dataset for previous year
  pastdate: "2019-01-01" 
            
  # First day of the month from LAST YEAR | Compiles Data for the most recent month of the previous year
  pstmonth: "2019-01-01" 
           
  # This is the first day of the next month (of last year) | Compiles Data for the most recent month of the previous year
  pstmonth2: "2019-02-01"  
---

### Introduction

This file is used to clean data from the city of St Louis and convert it into a .csv file which will be stored in my `data` folder. This file is complied by Logan Williams for use by the WUMCRC.

## Dependencies

```{r, message=FALSE}

#Load dependencies

library(dplyr)        #data cleaning
library(RODBC)        #ODBC database connectivity
library(ggplot2)      #chart making
library(here)         #file paths
library(readr)        #Write csv
library(writexl)      #write excel
library(lubridate)    #manipulate date time data
```

```{r}
# This code chunk creates the appropriate folder paths that are referred to in all of the .Rmd documents. 
# This code is necessary to knit and compile the powerpoint presentations.

here::here()
dir.create(getwd())
dir.create(here::here(file.path("results", params$year)))
dir.create(here::here(file.path("results", params$year, "yearly")))
dir.create(here::here(file.path("results", params$year, "yearly", "academy")))
dir.create(here::here(file.path("results", params$year, "yearly", "cwe")))
dir.create(here::here(file.path("results", params$year, "yearly", "dbplace")))
dir.create(here::here(file.path("results", params$year, "yearly", "ftnprk")))
dir.create(here::here(file.path("results", params$year, "yearly", "fpse")))
dir.create(here::here(file.path("results", params$year, "yearly", "lewis")))
dir.create(here::here(file.path("results", params$year, "yearly", "skinker")))
dir.create(here::here(file.path("results", params$year, "yearly", "vandy")))
dir.create(here::here(file.path("results", params$year, "yearly", "vstprk")))
dir.create(here::here(file.path("results", params$year, "yearly", "westend")))
dir.create(here::here(file.path("results", params$year, "yearly", "all_nbhds")))
dir.create(here::here(file.path("results", params$year, params$month)))
dir.create(here::here(file.path("results", params$year, params$month, "academy")))
dir.create(here::here(file.path("results", params$year, params$month, "cwe")))
dir.create(here::here(file.path("results", params$year, params$month, "dbplace")))
dir.create(here::here(file.path("results", params$year, params$month, "ftnprk")))
dir.create(here::here(file.path("results", params$year, params$month, "fpse")))
dir.create(here::here(file.path("results", params$year, params$month, "lewis")))
dir.create(here::here(file.path("results", params$year, params$month, "skinker")))
dir.create(here::here(file.path("results", params$year, params$month, "vandy")))
dir.create(here::here(file.path("results", params$year, params$month, "vstprk")))
dir.create(here::here(file.path("results", params$year, params$month, "westend")))
dir.create(here::here(file.path("results", params$year, params$month, "all_nbhds")))
dir.create(here::here(file.path("results", "presentations", params$year, params$month)))
dir.create(here::here(file.path("results", "presentations", params$year, "yearly")))
dir.create(here::here(file.path("data", params$year)))
dir.create(here::here(file.path("data", params$year, params$month)))
dir.create(here::here(file.path("data", params$year, params$month, "shapefiles")))
dir.create(here::here(file.path("data", params$pastyear, "yearly")))
```

### Temperary Code
```{r, message=FALSE}
library(readxl)
data <- read_excel(here::here("data", "PrmBldg.xlsx"))
```


```{r, include=FALSE}
# Set working directory
wd <- getwd()
setwd(wd)
#setwd("G:/Projects/Monthly-Reports/stl-building-permits")
```


```{r, include=FALSE}

#Import data

#channel <- odbcDriverConnect("Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=/data/working-db/bldgpermits/prmdbo
                             #G:/Projects/Monthly-Reports/stl-building-permits/permit-data-cleaning/prmbdo/prmbdo")
```


```{r, include=FALSE}

#Run SQL query to return data

#data <- sqlQuery( channel , paste ("select *
# from PrmBldg"))
```


```{r, include=FALSE}
data%>%
  
  #create year & month variables
  mutate(yr = format(as.Date(data$FirstDate,  format="%d/%m/%Y"), "%Y"))%>%
  mutate(month = format(as.Date(data$FirstDate, format="%d/%m/%Y"), "%m"))%>%
  
  # Use filter command to filter out permits without a cancellation date and with cost of $0
  filter(is.na(CancelDate))%>%
  filter(EstProjectCost != 0)%>% 

  # Filter out 10 neighborhoods we want to study
  filter(Nbrhd %in% c("38", "39", "46", "47", "48", "49", "51", "53", "54", "58"))%>%
  
  
  # Recode values to neighborood names
  mutate(nbhd_name = ifelse(grepl("38", Nbrhd), "Central West End",
                                             ifelse(grepl("39", Nbrhd), "Forest Park Southeast",
                                             ifelse(grepl("46", Nbrhd), "Skinker DeBaliviere",  
                                             ifelse(grepl("47", Nbrhd), "DeBaliviere Place",
                                             ifelse(grepl("48", Nbrhd), "West End",
                                             ifelse(grepl("49", Nbrhd), "Visitation Park",       
                                             ifelse(grepl("51", Nbrhd), "Academy",       
                                             ifelse(grepl("53", Nbrhd), "Fountain Park",       
                                             ifelse(grepl("54", Nbrhd), "Lewis Place",       
                                             ifelse(grepl("58", Nbrhd), "Vandeventer", NA)))))))))))%>%
  
  #create new_use variable
  mutate(new_use = ifelse(grepl("R2", NewUseGroup1), "Residential",
                                             ifelse(grepl("R3", NewUseGroup1), "Residential",
                                             ifelse(grepl("A2", NewUseGroup1), "Commercial",
                                             ifelse(grepl("A3", NewUseGroup1), "Commercial",
                                             ifelse(grepl("R1", NewUseGroup1), "Commercial",  
                                             ifelse(grepl("B", NewUseGroup1), "Institutional",
                                             ifelse(grepl("M", NewUseGroup1), "Commercial",
                                             ifelse(grepl("E", NewUseGroup1), "Institutional",       
                                             ifelse(grepl("I2", NewUseGroup1), "Institutional", 
                                             ifelse(grepl("I4", NewUseGroup1), "Institutional",
                                             ifelse(grepl("F1", NewUseGroup1), "Commercial",
                                             ifelse(grepl("U", NewUseGroup1), "Commercial", 
                                             ifelse(grepl("RESTAURANT", NewUse), "Commercial",
                                             ifelse(grepl("COMM/RESIDENT", NewUse), "Residential",
                                             ifelse(grepl("EVENT SPACE", NewUse), "Commercial",   
                                             ifelse(grepl("CHURCH", NewUse), "Institutional",
                                             ifelse(grepl("WAREHOUSE", NewUse), "Industrial",
                                             ifelse(grepl("PARKING GARAGE", NewUse), "Commercial",
                                             ifelse(grepl("PARKING LOT", NewUse), "Commercial",
                                             ifelse(grepl("CAFE", NewUse), "Commercial",
                                             ifelse(grepl("LOUNGE", NewUse), "Commercial",
                                             ifelse(grepl("NURSING HOME", NewUse), "Residential",
                                                    NA)))))))))))))))))))))))%>%
  
  # Create New Variables for Building Permits Greater/Less Than 50,000
  mutate(big_cost = ifelse(EstProjectCost >= 50000, 1, NA))%>%
  mutate(lil_cost = ifelse(EstProjectCost < 50000, 1, NA))%>%

  #This variable is specifically for individual neighborhood analysis
  mutate(lrgcost = ifelse(grepl("1", big_cost), "> $50,000", "< $50,000"))%>% 
  
  #create count variable
  group_by(nbhd_name, new_use)%>%
  mutate(count = n())%>%
  
  #rename handle
  rename(HANDLE = Handle)%>%
  
  #Drop unused variables using `select` function, assign to new `df` data frame
  select(AppType, CancelType, CityBlock, Parcel, OwnerCode, HANDLE, AddrNum,
                    StDir, StName, StType, UnitNum, OrigAddress, ProjectType, MainStrucType, AppDate,
                    IssueDate,CompleteDate, CancelDate, EstProjectCost, AppDescription, StrucType1,
                    NbrOfUnits, NewUse,NewUseGroup1, OldUse, OwnerName, OwnerCo, OwnerAddr, OwnerCity,
                    OwnerState, OwnerZIP, Nbrhd, FirstDate, LastDate, UpDateGeo, count, big_cost, lil_cost, lrgcost, new_use, nbhd_name, yr, month) -> df



```


```{r}
#write new cleaned data into .csv files

#current month
data_month <- filter(df, FirstDate >= as.Date(params$date) & FirstDate <= as.Date(params$enddate))
write_csv(data_month, here::here("data", params$year, params$month, "clean_data.csv"))

# This code creates a new dataset called `means` that contains a breakdown of building permits by neighborhood broken up by `new_use`. The new dataset contains the `mean` variable which is the mean `EstProjectCost`, a `count1` variable which is simply the number of building permits, a `high_cost` variable which is the number of housing permits whose `EstProjectCost` is greater than or equal to 50,000, and a `low_cost` varaiable which is the number of housing permits whose `EstProjectCost` is less than 50,000.
data_month %>%
  group_by(nbhd_name, new_use) %>%
  summarise(mean = mean(EstProjectCost), count1 = mean(count), high_cost = sum(big_cost, na.rm = TRUE), low_cost = sum(lil_cost, na.rm = TRUE)) -> means
write_csv(means, here::here("data", params$year, params$month, "mean_data.csv"))

#current year to date
data_year <- filter(df, FirstDate >= as.Date(params$ytd) & FirstDate <= as.Date(params$enddate))
write_csv(data_year, here::here("data", params$year, params$month, "ytd.csv"))

#last year this month
lstmonth <- filter(df, FirstDate >= as.Date(params$pstmonth) & FirstDate <= as.Date(params$pstmonth2))
write_csv(lstmonth, here::here("data", params$year, params$month, "lastmonth.csv"))

#last year to date
lastytd <- filter(df, FirstDate >= as.Date(params$pastdate) & FirstDate <= as.Date(params$pstmonth2))
write_csv(lastytd, here::here("data", params$year, params$month, "lastytd.csv"))

#last year data
lstyr <- filter(df, yr == params$pastyear)
write_csv(lstyr, here::here("data", params$pastyear, "yearly", "clean_year.csv"))

#5 year data
yr5 <- filter(df, yr >= (params$pastyear - 5) & yr <= params$pastyear)
write_csv(yr5, here::here("data", params$pastyear, "yearly", "5year.csv"))
```
