---
title: "Building Permit Descriptive Statistics"
author: "Logan Williams"
date: "2/24/2020"
output: powerpoint_presentation
params:
  month: January
  pastyear: 2019
  year: 2020
  date: "2020-01-01"
  pastdate: "2019-01-01"
---

## Introduction

This notebook creates a report of descriptive statistics 


```{r, message=FALSE, echo=FALSE}
#load dependencies
library(dplyr)      #data cleaning
library(here)       #file paths
library(readr)      #read csv
```

```{r, message=FALSE, echo=FALSE}
#load data
data <- read_csv(here("data", params$year, params$month, "bldprmt_clean.csv"))
```


## `EstProjectCost` Total

```{r, echo=FALSE}
# This code returns the average project cost by using the `mean` function.

mean(data$EstProjectCost)
```


## Number of Permits Total by Use

```{r, echo=FALSE}

#This code uses the `table` function to return how many permits are being used in each neighborhood.

table(data$nbhd_name)
```


## Average Project Cost by `new_use`

```{r, echo=FALSE}

#This code chunk calculates the mean `EstProjectCost` by `new_use` variable. You can also use a `by()` command for this and get the same result.

sapply(split(data$EstProjectCost, data$new_use), mean)
```


## Average Building Permit Cost by `nbhd_name`

```{r, echo=FALSE}

# This code chunk uses a `by()` command to give us the mean of `EstProjectCost` by `nbhd_name`

by(data$EstProjectCost, list(data$nbhd_name), mean)
```

