---
title: "St. Louis Central Corridor West Building Permits"
subtitle: "Monthly Report: January 2020" 
author: "Washington University Medical Center"
date: '(`r format(Sys.time(), "%B %d, %Y")`)'
output:
  powerpoint_presentation
always_allow_html: yes
params:
  
  #change EVERY month
  month: October
  year: 2020
  pastyear: 2019

# Compiles Year to Date Dataset for this year | Leave at January 1st 2020
  ytd: "2020-01-01" 
               
  # First day of current month | Change this each month
  date: "2020-10-01"   
  
  # First day of next month | Change this each month
  enddate: "2020-11-01"
           
  #Leave at January 1st of last year | Compiles Year to Date Dataset for previous year
  pastdate: "2019-01-01" 
            
  # First day of the month from LAST YEAR | Compiles Data for the most recent month of the previous year
  pstmonth: "2019-10-01" 
           
  # This is the first day of the next month (of last year) | Compiles Data for the most recent month of the previous year
  pstmonth2: "2019-11-01"  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Introduction

Before running this code make sure that all params are changed to the correct dates!

```{r, include=FALSE}
#load dependencies
library(dplyr)        # data manipulation
library(readr)        #download csv
library(here)         #file path management
library(kableExtra)   #data tables

# spatial packages
library(tmap)         # map layouts
library(tmaptools)    # tools for handeling spatial
library(sf)           # spatial data tools

#other packages
library(RColorBrewer) # cynthia brewer color palettes
library(viridis)      # color palettes
library(knitr)
library(ggplot2)      # plot making
library(formattable)  # currency values
library(lubridate)    # manipulate date time data
library(officer)      # powerpoint manipulation
library(flextable)    # nice tables
library(customLayout) # custom powerpoint layout
library(rlang)        # check for empty values
library(tidyr)        # used to drop NA
library(docxtractr)   #convert pptx to pdf
```


```{r, include=FALSE}
#load data
setwd('/Users/loganbogenut/Documents/GitHub/stl-building-permits')

df <- read_csv(here::here("data", params$year, params$month, "clean_data.csv"))
ytd <- read_csv(here::here("data", params$year, params$month,  "ytd.csv"))
lastmonth <- read_csv(here::here("data", params$year, params$month,  "lastmonth.csv"))
lastytd <- read_csv(here::here("data", params$year, params$month,  "lastytd.csv"))
avg <- read_csv(here::here("data", params$year, params$month,  "mean_data.csv"))
month6 <- read_csv(here::here("data", params$year, params$month,  "month6.csv"))

load(file = here::here("data", "basemap_tiles", "mapbox-tiles.rda"))
load(file = here::here("data", "basemap_tiles", "boundaries.rda"))
load(file = here::here("data", "basemap_tiles", "nbhd-boundaries.rda"))

#create powerpoint
report <- read_pptx()

neighborhoods <- c(38, 39, 46:49, 51, 53, 54, 58)
names <- c("Central West End", "Forest Park Southeast", "Skinker DeBaliviere", "DeBaliviere Place", "West End", "Visitation Park", "Academy", "Fountain Park", "Lewis Place", "Vandeventer")
use <- c("Industrial", "Institutional", "Residential", "Commercial")
```

```{r, include=FALSE}
#import parcel data
st_read(here::here("/data/working-db/parcels", "prcl.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> prcl
```

```{r, include=FALSE}
#make sure both are numeric
df$HANDLE <- as.numeric(df$HANDLE)
prcl$HANDLE <- as.numeric(prcl$HANDLE)

#merge by handle
merge <- df%>%
  merge(prcl, by = "HANDLE")
```

```{r}
#create custom color palette for plots
cols <- c("Industrial" = "#e41a1c", "Residential" = "#377eb8", "Commercial" = "#4daf4a", "Institutional" = "#984ea3")

# summary note colors
reg24 <- fp_text(color = 'black', font.size = 24)
reg20 <- fp_text(color = 'black', font.size = 20)
boldline <- fp_text(color = "black", font.size = 28, bold = TRUE, underlined = TRUE)
bold <- fp_text(color = "black", font.size = 24, bold = TRUE)
```

```{r officer layout}
#create custom powerpoint layout
lay <- lay_new(matrix(1:2)) 
title <- lay_new(1, widths = 2, heights = 2)
layout <- lay_bind_row(title, lay, heights = c(1,6))
lay_show(layout)

offlayout <- phl_layout(layout,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))

lay1 <- lay_new(matrix(1:4, nc = 2), widths = c(2,2), heights = c(2,1)) 
title1 <- lay_new(1, widths = 2, heights = 2)
layout1 <- lay_bind_row(title1, lay1, heights = c(1,6))
lay_show(layout1)

offlayout01 <- phl_layout(layout1,
    margins = c(0, 0, 0, 0),
    innerMargins = rep(0.15,4))
```

```{r}
#title slide
report%>%
  add_slide(layout = "Title Slide", master = "Office Theme")%>%
  ph_with(value = "St. Louis Central Corridor West Building Permits", location = ph_location_type(type = "ctrTitle"))%>%
  ph_with(paste("Monthly Report:", params$month, params$year, sep = " "), location = ph_location_type(type = "subTitle"))%>%
  ph_with(value = "Washington University Medical Center", location = ph_location_type(type = "dt")) -> report

#add STL map reference
report%>%
add_slide()%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "spat_ref.png"), height = 5, width = 9),
          ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("St. Louis Neighborhood Spatial Reference", 
               location = ph_location_type(
                 type = "title") )-> report
```



### All Neighborhoods: Summary

```{r}
# Average cost by neighborhood for each `new_use`

ggplot(avg, aes(x = nbhd_name, y = mean, fill = new_use)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(position = "dodge", stat="identity") +
  theme(plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()) +
  ylab("Cost") +
  labs(fill = "New Use") +
  scale_y_continuous(labels = scales::dollar_format())+
  coord_flip()

ggsave(here::here("results", params$year, params$month, "all_nbhds", "allnbhd_plot.png"), 
       width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "all_nbhds", "allnbhd_plot.png"), width = 9, height = 5),
          location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Neighborhood Summary: Average Building Permit Cost", 
               location = ph_location_type(
                 type = "title") )-> report

```

```{r, echo = FALSE}
#create summary tables for current month and past 6 months
df%>%
  group_by(nbhd_name)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(nbhd_name, mean, count, sum) -> table

names[!(names %in% table$nbhd_name)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, nbhd_name = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., nbhd_name) -> table

  
month6%>%
  group_by(nbhd_name)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(nbhd_name, mean, count, sum) -> table1

names[!(names %in% table1$nbhd_name)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, nbhd_name = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., nbhd_name) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(nbhd_name = "Neighborhood", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(nbhd_name = "Neighborhood", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide()%>%
  ph_with("Neighborhood Summary", 
               location = ph_location_type(
                 type = "title"))%>%
  phl_with_flextable(olay = offlayout01, 2, flex)%>%
  phl_with_flextable(olay = offlayout01, 4, flex01) -> report
```


### Forest Park Southeast

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 39)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "fpse.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("Forest Park Southeast", 
               location = ph_location_type(
                 type = "title") )-> report
```


```{r FPSE ytd summary notes}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 39)
nbhd19 <- filter(lastmonth, Nbrhd == 39)
tot20 <- filter(ytd, Nbrhd ==39)
tot19 <- filter(lastytd, Nbrhd == 39)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "Forest Park Southeast: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create fpse color palette
sub <- filter(df, nbhd_name == "Forest Park Southeast")
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r FPSE Building Permit Mapping, include = FALSE}
if("Forest Park Southeast" %in% df$nbhd_name){

#write shapefile
fpse_shp <- filter(merge, nbhd_name == "Forest Park Southeast")
st_write(fpse_shp, here::here("data", params$year, params$month, "shapefiles", "fpse.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "fpse.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> fpse

#mapping
tm_shape(fpse_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 39) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  fpse%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> fpse_map

#save map as .jpeg
tmap_save(fpse_map, file = here::here("results", params$year, params$month, "fpse", "fpse_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "fpse", "fpse_use.jpeg"), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Forest Park Southeast", 
               location = ph_location_type(
                 type = "title") )-> report
  }
```

```{r FPSE summary table, echo=FALSE}
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "Forest Park Southeast")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table

  
month6%>%
  filter(nbhd_name == "Forest Park Southeast")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use)  -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Neighborhood Summary", 
               location = ph_location_type(
                 type = "title")) -> report
```

```{r, echo=FALSE}
if("Forest Park Southeast" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 39,]) < 15){
    
    #create in depth summary table
  df%>%
  filter(nbhd_name == "Forest Park Southeast")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "address")%>%
    set_caption("Forest Park Southeast Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "Forest Park Southeast Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```


```{r fpse plot, echo=FALSE, message=FALSE}
if("Forest Park Southeast" %in% df$nbhd_name){
fpse <- filter(df, nbhd_name == "Forest Park Southeast")
ggplot(fpse, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> fpse_plot

ggsave(here::here("results",  params$year, params$month, "fpse", "fpse_cost.png"), 
       plot = fpse_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "fpse", "fpse_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE)%>%
  ph_with(value = "Forest Park Southeast Permit Cost Breakdown", 
          location = ph_location_type(type = "title")) -> report
}
```


### Central West End

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 38)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "cwe.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("Central West End", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r CWE ytd summary notes}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 38)
nbhd19 <- filter(lastmonth, Nbrhd == 38)
tot20 <- filter(ytd, Nbrhd ==38)
tot19 <- filter(lastytd, Nbrhd == 38)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "Central West End: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create cwe color palette
sub <- filter(df, nbhd_name == "Central West End")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r CWE Building Permit Mapping, include = FALSE}

if("Central West End" %in% df$nbhd_name){

#write shapefile  
cwe_shp <- filter(merge, nbhd_name == "Central West End")
st_write(cwe_shp, here::here("data", params$year, params$month, "shapefiles", "cwe.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "cwe.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> cwe

#map shapefile
tm_shape(cwe_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 38) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  cwe%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> cwe_map

#save map as .jpeg
tmap_save(cwe_map, file = here::here("results", params$year, params$month, "cwe", "cwe_use.jpeg"),
          width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "cwe", "cwe_use.jpeg"), width = 9, height = 5), location = ph_location_type(type="body"), use_loc_size = FALSE)%>%
  ph_with("Central West End", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r, echo=FALSE}
if("Central West End" %in% df$nbhd_name){
    
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "Central West End")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use)  -> table

  
month6%>%
  filter(nbhd_name == "Central West End")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use)  -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Central West End", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r CWE summary table, echo = FALSE}
if("Central West End" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 38,]) < 15){
  
  #create in depth summary table
  df%>%
  filter(nbhd_name == "Central West End")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "address")%>%
    set_caption("Central West End Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "Central West End Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```

```{r CWE plot, echo=FALSE, message=FALSE}
if("Central West End" %in% df$nbhd_name){
cwe <- filter(df, nbhd_name == "Central West End")
ggplot(cwe, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> cwe_plot

ggsave(here::here("results",  params$year, params$month, "cwe", "cwe_cost.png"), 
       plot = cwe_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "Cental West End Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
  ph_with(external_img(here::here("results", params$year, params$month, "cwe", "cwe_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE) -> report
}
```

### DeBaliviere Place

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 47)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "dbplace.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("DeBaliviere Place", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r dbplace ytd summary notes}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 47)
nbhd19 <- filter(lastmonth, Nbrhd == 47)
tot20 <- filter(ytd, Nbrhd == 47)
tot19 <- filter(lastytd, Nbrhd == 47)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "DeBaliviere Place: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create DeBaliviere Place color palette
sub <- filter(df, nbhd_name == "DeBaliviere Place")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r DeBaliviere Place Building Permit Mapping, include = FALSE}
if("DeBaliviere Place" %in% df$nbhd_name){

#write shapefile  
dbplace_shp <- filter(merge, nbhd_name == "DeBaliviere Place")
st_write(dbplace_shp, here::here("data", params$year, params$month, "shapefiles", "dbplace.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "dbplace.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> dbplace

#map shapefile
tm_shape(dbp_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 47) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  dbplace%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> dbplace_map

#save map as .jpeg
tmap_save(dbplace_map, file = here::here("results", params$year, params$month, "dbplace", "dbplace_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "dbplace", "dbplace_use.jpeg"), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("DeBaliviere Place", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r, echo=FALSE}
if("DeBaliviere Place" %in% df$nbhd_name){
    
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "DeBaliviere Place")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use)  -> table

  
month6%>%
  filter(nbhd_name == "DeBaliviere Place")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("DeBaliviere Place", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r dbplace summary table, echo = FALSE}
if("DeBaliviere Place" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 47,]) < 15){
    
  #create in depth summary table
  df%>%
  filter(nbhd_name == "DeBaliviere Place")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "Address")%>%
    set_caption("DeBaliviere Place Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "DeBaliviere Place Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```

```{r dbplace plot, echo=FALSE, message=FALSE}
if("DeBaliviere Place" %in% df$nbhd_name){
dbplace <- filter(df, nbhd_name == "DeBaliviere Place")
ggplot(dbplace, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> dbplace_plot

ggsave(here::here("results",  params$year, params$month, "dbplace", "dbplace_cost.png"), 
       plot = dbplace_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "DeBaliviere Place Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
  ph_with(external_img(here::here("results", params$year, params$month, "dbplace", "dbplace_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE) -> report
}
```

### Skinker DeBaliviere

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 46)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "skinker_db.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("Skinker DeBaliviere", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r skinker ytd summary notes}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 46)
nbhd19 <- filter(lastmonth, Nbrhd == 46)
tot20 <- filter(ytd, Nbrhd == 46)
tot19 <- filter(lastytd, Nbrhd == 46)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "Skinker DeBaliviere: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create Skinker DeBaliviere color palette
sub <- filter(df, nbhd_name == "Skinker DeBaliviere")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Skinker DeBaliviere Building Permit Mapping, include = FALSE}
if("Skinker DeBaliviere" %in% df$nbhd_name){

#write shapefile
skinker_shp <- filter(merge, nbhd_name == "Skinker DeBaliviere")
st_write(skinker_shp, here::here("data", params$year, params$month, "shapefiles", "skinkerdb.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "skinkerdb.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> skinker

#mapping
tm_shape(sdb_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 46) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  skinker%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> skinker_map

#save map as .jpeg
tmap_save(skinker_map, file = here::here("results", params$year, params$month, "skinker", "skinker_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "skinker", "skinker_use.jpeg"), width = 9, height = 5), 
          location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Skinker DeBaliviere", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r Skinker DeBaliviere summary table, echo = FALSE}
if("Skinker DeBaliviere" %in% df$nbhd_name){
    
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "Skinker DeBaliviere")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use)  -> table

  
month6%>%
  filter(nbhd_name == "Skinker DeBaliviere")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Skinker DeBaliviere", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r, echo=FALSE}
if("Skinker DeBaliviere" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 46,]) < 15){
  
  #create in depth summary table
  df%>%
  filter(nbhd_name == "Skinker DeBaliviere")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)

#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "Address")%>%
    set_caption("Skinker DeBaliviere Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "Skinker DeBaliviere Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```

```{r skinker plot, echo=FALSE, message=FALSE}
if("Skinker DeBaliviere" %in% df$nbhd_name){
skinker <- filter(df, nbhd_name == "Skinker DeBaliviere")
ggplot(skinker, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> skinker_plot

ggsave(here::here("results",  params$year, params$month, "skinker", "skinker_cost.png"),
       plot = skinker_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "Skinker DeBaliviere Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
  ph_with(external_img(here::here("results", params$year, params$month, "skinker", "skinker_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE) -> report
}
```


### West End

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 48)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "westend.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("West End", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r West End ytd summary notes}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 48)
nbhd19 <- filter(lastmonth, Nbrhd == 48)
tot20 <- filter(ytd, Nbrhd == 48)
tot19 <- filter(lastytd, Nbrhd == 48)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "West End: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create West End color palette
sub <- filter(df, nbhd_name == "West End")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r West End Building Permit Mapping, include = FALSE}

if("West End" %in% df$nbhd_name){

#write shapefile
westend_shp <- filter(merge, nbhd_name == "West End")
st_write(westend_shp, here::here("data", params$year, params$month, "shapefiles", "westend.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "westend.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> westend

#mapping
tm_shape(we_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 48) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  westend%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> westend_map

#save map as .jpeg
tmap_save(westend_map, file = here::here("results", params$year, params$month, "westend", "westend_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "westend", "westend_use.jpeg"), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("West End", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r West End summary table, echo=FALSE}
if("West End" %in% df$nbhd_name){
  
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "West End")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table

  
month6%>%
  filter(nbhd_name == "West End")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("West End", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r West End summary table, echo=FALSE}
if("West End" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 48,]) < 15){

    #create in depth summary table
  df%>%
  filter(nbhd_name == "West End")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "Address")%>%
    set_caption("West End Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "West End Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```


```{r westend plot, echo=FALSE, message=FALSE}
if("West End" %in% df$nbhd_name){
westend <- filter(df, nbhd_name == "West End")
ggplot(westend, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> westend_plot

ggsave(here::here("results",  params$year, params$month, "westend", "westend_cost.png"), 
       plot = westend_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "West End Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
 ph_with(external_img(here::here("results", params$year, params$month, "westend", "westend_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE) -> report
}
```


### Visitation Park

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 49)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "visitation_park.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("Visitation Park", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r vstprk ytd summary notes}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 49)
nbhd19 <- filter(lastmonth, Nbrhd == 49)
tot20 <- filter(ytd, Nbrhd == 49)
tot19 <- filter(lastytd, Nbrhd == 49)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "Visitation Park: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create Visitation Park color palette
sub <- filter(df, nbhd_name == "Visitation Park")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Visitation Park Building Permit Mapping, include = FALSE}
if("Visitation Park" %in% df$nbhd_name){
  
#write shapefile
visit_shp <- filter(merge, nbhd_name == "Visitation Park")
st_write(visit_shp, here::here("data", params$year, params$month, "shapefiles", "vstprk.shp"), 
         delete_dsn = TRUE)
  
#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "vstprk.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> vstprk

#map shapefile
tm_shape(vp_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 49) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  vstprk%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> vstprk_map

#save map as .jpeg
tmap_save(vstprk_map, file = here::here("results", params$year, params$month, "vstprk", "vstprk_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "vstprk", "vstprk_use.jpeg"), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Visitation Park", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r, echo = FALSE}
if("Visitation Park" %in% df$nbhd_name){
    
 #create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "Visitation Park")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table

  
month6%>%
  filter(nbhd_name == "Visitation Park")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Visitation Park", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r, echo=FALSE}
if("Visitation Park" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 49,]) < 15){
  
  #create in depth summary table
  df%>%
  filter(nbhd_name == "Visitation Park")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "Address")%>%
    set_caption("Visitation Park Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "Visitation Park Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```

```{r vstprk plot, echo=FALSE, message=FALSE}
if("Visitation Park" %in% df$nbhd_name){
vstprk <- filter(df, nbhd_name == "Visitation Park")
ggplot(vstprk, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> vstprk_plot

ggsave(here::here("results",  params$year, params$month, "vstprk", "vstprk_cost.png"), 
       plot = vstprk_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "Visitation Park Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
  ph_with(external_img(here::here("results", params$year, params$month, "vstprk", "vstprk_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE) -> report
}
```


### Academy

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 51)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "academy.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("Academy", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r Academy ytd summary}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 51)
nbhd19 <- filter(lastmonth, Nbrhd == 51)
tot20 <- filter(ytd, Nbrhd == 51)
tot19 <- filter(lastytd, Nbrhd == 51)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "Academy: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create Academy color palette
sub <- filter(df, nbhd_name == "Academy")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Academy Building Permit Mapping, include = FALSE}
if("Academy" %in% df$nbhd_name){
  
#write shapefile  
  academy_shp <- filter(merge, nbhd_name == "Academy")
  st_write(academy_shp, here::here("data", params$year, params$month, "shapefiles", "academy.shp"), 
         delete_dsn = TRUE)


#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "academy.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> academy

#tm mapping
tm_shape(ac_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 51) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  academy%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> academy_map

#save map as .jpeg
tmap_save(academy_map, file = here::here("results", params$year, params$month, "academy", "ac_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "academy", "ac_use.jpeg"), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Academy", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r Academy summary table, echo = FALSE}
if("Academy" %in% df$nbhd_name){
    
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "Academy")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table

  
month6%>%
  filter(nbhd_name == "Academy")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Academy", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r Academy summary table, echo=FALSE}
if("Academy" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 51,]) < 15){
  
  #create in depth summary table
  df%>%
  filter(nbhd_name == "Academy")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "Address")%>%
    set_caption("Academy Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "Academy Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```


```{r Academy plot, echo=FALSE, message=FALSE}
if("Academy" %in% df$nbhd_name){
academy <- filter(df, nbhd_name == "Academy")
ggplot(academy, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> ac_plot

ggsave(here::here("results",  params$year, params$month, "academy", "ac_cost.png"), 
       plot = ac_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "Academy Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
  ph_with(external_img(here::here("results", params$year, params$month, "academy", "ac_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE) -> report
}
```


### Fountain Park

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 53)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "fountain_park.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("Fountain Park", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r ftnprk ytd summary}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 53)
nbhd19 <- filter(lastmonth, Nbrhd == 53)
tot20 <- filter(ytd, Nbrhd == 53)
tot19 <- filter(lastytd, Nbrhd == 53)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "Fountain Park: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create Fountain Park color palette
sub <- filter(df, nbhd_name == "Fountain Park")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Fountain Park Building Permit Mapping, include = FALSE}
if("Fountain Park" %in% df$nbhd_name){

#write shapefile
ftnprk_shp <- filter(merge, nbhd_name == "Fountain Park")
st_write(ftnprk_shp, here::here("data", params$year, params$month, "shapefiles", "ftnprk.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "ftnprk.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> ftnprk

#map shapefile
tm_shape(fp_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 53) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  ftnprk%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> ftnprk_map

#save map as .jpeg
tmap_save(ftnprk_map, file = here::here("results", params$year, params$month, "ftnprk", "ftnprk_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "ftnprk", "ftnprk_use.jpeg"), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Fountain Park", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r Fountain Park summary table, echo = FALSE}
if("Fountain Park" %in% df$nbhd_name){
    
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "Fountain Park")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table

  
month6%>%
  filter(nbhd_name == "Fountain Park")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Fountain Park", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r, echo=FALSE}
if("Fountain Park" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 53,]) < 15){
  
  #create in depth summary table
  df%>%
  filter(nbhd_name == "Fountain Park")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "Address")%>%
    set_caption("Fountain Park Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "Fountain Park Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```


```{r ftnprk plot, echo=FALSE, message=FALSE}
if("Fountain Park" %in% df$nbhd_name){
ftnprk <- filter(df, nbhd_name == "Fountain Park")
ggplot(ftnprk, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> ftnprk_plot

ggsave(here::here("results",  params$year, params$month, "ftnprk", "ftnprk_cost.png"), 
       plot = ftnprk_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "Fountain Park Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
  ph_with(external_img(here::here("results", params$year, params$month, "ftnprk", "ftnprk_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE) -> report
}
```

### Lewis Place

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 54)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "lewis_place.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("Lewis Place", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r Lewis Place ytd summary}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 54)
nbhd19 <- filter(lastmonth, Nbrhd == 54)
tot20 <- filter(ytd, Nbrhd == 54)
tot19 <- filter(lastytd, Nbrhd == 54)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "Lewis Place: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create Lewis Place color palette
sub <- filter(df, nbhd_name == "Lewis Place")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Lewis Place Building Permit Mapping, include = FALSE}

if("Lewis Place" %in% df$nbhd_name){

#write shapefile
lewis_shp <- filter(merge, nbhd_name == "Lewis Place")
st_write(lewis_shp, here::here("data", params$year, params$month, "shapefiles", "lewis.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "lewis.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> lewis

#map shapefile
tm_shape(lp_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 54) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  lewis%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> lewis_map

#save map as .jpeg
tmap_save(lewis_map, file = here::here("results", params$year, params$month, "lewis", "lewis_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "lewis", "lewis_use.jpeg"), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Lewis Place", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r, echo=FALSE}
if("Lewis Place" %in% df$nbhd_name){
    
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "Lewis Place")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table

  
month6%>%
  filter(nbhd_name == "Lewis Place")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Lewis Place", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r, echo=FALSE}
if("Lewis Place" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 54,]) < 15){
  
  #create in depth summary table
  df%>%
  filter(nbhd_name == "Lewis Place")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "Address")%>%
    set_caption("Lewis Place Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "Lewis Place Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```

```{r Lewis plot, echo=FALSE, message=FALSE}
if("Lewis Place" %in% df$nbhd_name){
lewis <- filter(df, nbhd_name == "Lewis Place")
ggplot(lewis, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> lewis_plot

ggsave(here::here("results",  params$year, params$month, "lewis", "lewis_cost.png"), 
       plot = lewis_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "Lewis Place Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
  ph_with(external_img(here::here("results", params$year, params$month, "lewis", "lewis_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE) -> report
}
```


### Vandeventer

```{r}
#create mean, median, range stats
nbhd20 <- filter(df, Nbrhd == 58)
mean <- mean(nbhd20$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd20$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd20$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd20$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "vandeventer.png"), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with("Vandeventer", 
               location = ph_location_type(
                 type = "title") )-> report
```

```{r vandy ytd summary}
#filter out neighborhood
nbhd20 <- filter(df, Nbrhd == 58)
nbhd19 <- filter(lastmonth, Nbrhd == 58)
tot20 <- filter(ytd, Nbrhd == 58)
tot19 <- filter(lastytd, Nbrhd == 58)

#create cost and year to date variables for each year
bp20 <- nrow(nbhd20)
bp19 <- nrow(nbhd19)
cost20 <- mean(nbhd20$EstProjectCost)
cost20 <- currency(cost20, digits = 0L)
if(is.nan(cost20)){cost20[is.nan(cost20)] <- 0}
cost19 <- mean(nbhd19$EstProjectCost)
cost19 <- currency(cost19, digits = 0L)
if(is.nan(cost19)){cost19[is.nan(cost19)] <- 0}
bptot20 <- nrow(tot20)
bptot19 <- nrow(tot19)
totcost20 <- mean(tot20$EstProjectCost)
totcost20 <- currency(totcost20, digits = 0L)
if(is.nan(totcost20)){totcost20[is.nan(totcost20)] <- 0}
totcost19 <- mean(tot19$EstProjectCost)
totcost19 <- currency(totcost19, digits = 0L)
if(is.nan(totcost19)){totcost19[is.nan(totcost19)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp20 - bp19)/bp19
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost20 - cost19)/cost19
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd20 <- (bptot20 - bptot19)/bptot19
pct_chg_ytd20 <- percent(pct_chg_ytd20)
if(is.nan(pct_chg_ytd20)){pct_chg_ytd20[is.nan(pct_chg_ytd20)] <- 0}
if(is.infinite(pct_chg_ytd20)){pct_chg_ytd20[is.infinite(pct_chg_ytd20)] <- "Infinite"}
pct_chg_cost20 <- (totcost20 - totcost19)/totcost19
pct_chg_cost20 <- percent(pct_chg_cost20)
if(is.nan(pct_chg_cost20)){pct_chg_cost20[is.nan(pct_chg_cost20)] <- 0}
if(is.infinite(pct_chg_cost20)){pct_chg_cost20[is.infinite(pct_chg_cost20)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp20, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot20, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd20 == 0, '#00B0F0', ifelse(pct_chg_ytd20 > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost20 == 0, "#00B0F0", ifelse(pct_chg_cost20 > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", params$pastyear, " (", bp19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost20), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", params$pastyear, " (", cost19, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd20, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", params$pastyear, " (", bptot19, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost20), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost20, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", params$pastyear, " (", totcost19, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = "Vandeventer: Summary Notes", location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report
```

```{r}
#create Vandeventer color palette
sub <- filter(df, nbhd_name == "Vandeventer")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Vandeventer Building Permit Mapping, include = FALSE}
if("Vandeventer" %in% df$nbhd_name){
  
#write shapefile
vandy_shp <- filter(merge, nbhd_name == "Vandeventer")
st_write(vandy_shp, here::here("data", params$year, params$month, "shapefiles", "vandy.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", "vandy.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> vandy

#mapping
tm_shape(vd_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 58) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  vandy%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> vandy_map

#save map as .jpeg
tmap_save(vandy_map, file = here::here("results", params$year, params$month, "vandy", "vandy_use.jpeg"), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "vandy", "vandy_use.jpeg"), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Vandeventer", 
               location = ph_location_type(
                 type = "title") )-> report
}
```

```{r vandy summary table, echo=FALSE}
if("Vandeventer" %in% df$nbhd_name){
    
#create summary tables for current month and past 6 months
df%>%
  filter(nbhd_name == "Vandeventer")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table

  
month6%>%
  filter(nbhd_name == "Vandeventer")%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table1

#make a currency value
table$mean <- currency(table$mean, digits = 0L)
table1$mean <- currency(table1$mean, digits = 0L)
table$sum <- currency(table$sum, digits = 0L)
table1$sum <- currency(table1$sum, digits = 0L)
  
#make summary tables
  flextable(table)%>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex
  
  flextable(table1)%>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Vandeventer", 
               location = ph_location_type(
                 type = "title")) -> report
}
```

```{r, echo=FALSE}
if("Vandeventer" %in% df$nbhd_name){
  if(nrow(df[df$Nbrhd == 58,]) < 15){
  
  #create in depth summary table
  df%>%
  filter(nbhd_name == "Vandeventer")%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "Address")%>%
    set_caption("Vandeventer Individual Permit Breakdown") -> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = "Vandeventer Individual Permit Breakdown", location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}}
```

```{r vandy plot, echo=FALSE, message=FALSE}
if("Vandeventer" %in% df$nbhd_name){
vandy <- filter(df, nbhd_name == "Vandeventer")
ggplot(vandy, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> vandy_plot

ggsave(here::here("results",  params$year, params$month, "vandy", "vandy_cost.png"), 
       plot = vandy_plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(value = "Vandeventer Permit Cost Breakdown", location = ph_location_type(type = "title"))%>%
  ph_with(external_img(here::here("results", params$year, params$month, "vandy", "vandy_cost.png"),
                       width = 9, height = 5), location = ph_location_type(type = "body"), 
                       use_loc_size = FALSE) -> report
}
```

```{r}
  # additional notes slide
report%>%
  add_slide()%>%
  ph_with(value = "Additional Notes", location = ph_location_type(type = "title"))%>%
  ph_with(c("Data retreived from https://www.stlouis-mo.gov/data/", "Building permits with a cost of $0 were dropped", "Building permits that were cancelled were dropped", "Infinite change indicates 0 permits in the current or previous time period/comparison month so there was a overall increase or decrease"), location = ph_location_type(type = "body")) -> report
```


```{r}
# save powerpoint report
print(report, target = here::here("results", "presentations",  params$year, params$month, paste("bldgprmt_report", params$month, params$year, ".pptx", sep = "")))

#delete any existing fpse-bot-cwe-mc file in the Shiny app
mydir <- "/Users/loganbogenut/Documents/GitHub/crime_interactive/crime_interactive/www/"
file.remove(file.path(mydir, dir(path = mydir, pattern = "monthly_report")))

#convert & save powerpoint as PDF to Shiny app
convert_to_pdf(path = here::here("results", "presentations", params$year, params$month, paste("bldgprmt_report", params$month, params$year, ".pptx", sep = "")),
               pdf_file = sub("[.]pptx", ".pdf", paste("~/Documents/GitHub/crime_interactive/crime_interactive/www/", "bldgprmt_report", params$month, params$year, ".pptx", sep = "")))

# This code cleans our Global Environment and gives you a nice lil' message

rm(list = ls())
print("NICE JOB! You successfully ran all your code. Have an awesome day :)")
```

