---
title: "monthly-bldg-permit-report"
author: "Logan Williams"
date: "3/11/2021"
output: html_document
params:
#change EVERY month
  month: December
  year: 2021
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
#load dependencies
library(dplyr)        # data manipulation
library(readr)        #download csv
library(here)         #file path management
library(kableExtra)   #data tables

# spatial packages
library(tmap)         # map layouts
library(tmaptools)    # tools for handeling spatial
library(sf)           # spatial data tools

#other packages
library(RColorBrewer) # cynthia brewer color palettes
library(viridis)      # color palettes
library(knitr)
library(ggplot2)      # plot making
library(formattable)  # currency values
library(lubridate)    # manipulate date time data
library(officer)      # powerpoint manipulation
library(flextable)    # nice tables
library(customLayout) # custom powerpoint layout
library(rlang)        # check for empty values
library(tidyr)        # used to drop NA
library(docxtractr)   #convert pptx to pdf
library(gateway)      #get STL spatial boundaries
library(grid)
```

```{r, include=FALSE}
#load data
#setwd('/Users/loganbogenut/Documents/GitHub/stl-building-permits')

load(file = here::here("data", params$year, params$month, "clean-permit-data.rda"))
load(file = here::here("data", "basemap_tiles", "mapbox-tiles.rda"))
load(file = here::here("data", "basemap_tiles", "boundaries.rda"))
load(file = here::here("data", "basemap_tiles", "nbhd-boundaries.rda"))

#create powerpoint
report <- read_pptx()

bound <- gw_get_data("Neighborhoods", "sf") #get neighborhood boundaries
nbhd_num <- c("38", "39", "46", "47", "48", "49", "51", "53", "54", "58")
names <- c("Central West End", "Forest Park Southeast", "Skinker DeBaliviere", "DeBaliviere Place", "West End", "Visitation Park", "Academy", "Fountain Park", "Lewis Place", "Vandeventer")
use <- c("Industrial", "Residential", "Commercial")
```

```{r, include=FALSE}
#import parcel data
st_read(here::here("data", "working-db", "parcels", "prcl.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> prcl
```

```{r, include=FALSE}
#make sure both are numeric
data_month$HANDLE <- as.numeric(data_month$HANDLE)
prcl$HANDLE <- as.numeric(prcl$HANDLE)

#merge by handle
merge <- data_month%>%
  merge(prcl, by = "HANDLE")
```

```{r}
#create custom color palette for plots
cols <- c("Industrial" = "#e41a1c", "Residential" = "#377eb8", "Commercial" = "#4daf4a")

# summary note colors
reg24 <- fp_text(color = 'black', font.size = 24)
reg20 <- fp_text(color = 'black', font.size = 20)
boldline <- fp_text(color = "black", font.size = 28, bold = TRUE, underlined = TRUE)
bold <- fp_text(color = "black", font.size = 24, bold = TRUE)
```

```{r officer layout}
#create custom powerpoint layout
lay <- lay_new(matrix(1:2)) 
title <- lay_new(1, widths = 2, heights = 2)
layout <- lay_bind_row(title, lay, heights = c(1,6))
lay_show(layout)

offlayout <- phl_layout(layout,
    margins = c(0.25, 0.25, 0.25, 0.25),
    innerMargins = rep(0.15,4))

lay1 <- lay_new(matrix(1:4, nc = 2), widths = c(2,2), heights = c(2,1)) 
title1 <- lay_new(1, widths = 2, heights = 2)
layout1 <- lay_bind_row(title1, lay1, heights = c(1,6))
lay_show(layout1)

offlayout01 <- phl_layout(layout1,
    margins = c(0, 0, 0, 0),
    innerMargins = rep(0.15,4))
```

```{r}
# All Neighborhood Building Permit Map
merge_sf <- st_as_sf(merge)

bound%>%
filter(NHD_NUM %in% nbhd_num) -> bound_sub

#inset map
bound%>%
tm_shape()+
  tm_fill(col = "grey")+
  tm_borders(col = "white")+
  bound_sub%>%
  tm_shape()+
  tm_fill(col = "forestgreen")+
  tm_borders(col = "white") -> inset

bound_sub%>%
tm_shape()+
  tm_fill(col = "grey")+
  tm_borders(col = "white")+
  merge_sf%>%
  tm_shape() +
  tm_bubbles(size = .25,
               col = "new_use",
               palette = "Set1",
               title.col = "Building Permit Type") +
  tm_credits("Source: City of St. Louis", position = c("left", "BOTTOM"), size = .5) +
    tm_credits(paste("Date Created:", Sys.Date()), position = c("right", "BOTTOM"), size = .5)+
  tm_layout(
    main.title = paste("St. Louis Central Corridor West\nBuilding Permits -", params$month, params$year),
    main.title.position = "center",
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom"))-> map

tmap_save(map, insets_tm = inset, insets_vp = viewport(0.8, 0.75, width = 0.4, height = 0.4), file = here::here("results", params$year, params$month, "all_nbhds", "allbldg_map.jpeg"), width = 10.5, height = 5.9, units = "in")
```

```{r}
#title slide
report%>%
  add_slide(layout = "Title Slide", master = "Office Theme")%>%
  ph_with(value = "St. Louis Central Corridor West Building Permits", location = ph_location_type(type = "ctrTitle"))%>%
  ph_with(paste("Monthly Report:", params$month, params$year, sep = " "), location = ph_location_type(type = "subTitle"))%>%
  ph_with(value = "Washington University Medical Center", location = ph_location_type(type = "dt")) -> report

#add STL map reference
report%>%
add_slide()%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", "spat_ref.png"), height = 5, width = 9),
          ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("St. Louis Neighborhood Spatial Reference", 
               location = ph_location_type(
                 type = "title") )-> report
```

### All Neighborhoods: Summary

```{r}
# Average cost by neighborhood for each `new_use`

ggplot(means, aes(x = nbhd_name, y = mean, fill = new_use)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(position = "dodge", stat="identity") +
  theme(plot.title = element_text(hjust = 0.5),
    axis.title.y = element_blank()) +
  ylab("Cost") +
  labs(fill = "New Use") +
  scale_y_continuous(labels = scales::dollar_format())+
  coord_flip()

ggsave(here::here("results", params$year, params$month, "all_nbhds", "allnbhd_plot.png"), 
       width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, "all_nbhds", "allnbhd_plot.png"), width = 9, height = 5),
          location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with("Neighborhood Summary: Average Building Permit Cost", 
               location = ph_location_type(
                 type = "title") )-> report

```

```{r, echo = FALSE}
#create summary tables for current month and past 6 months
data_month%>%
  group_by(nbhd_name)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(nbhd_name, mean, count, sum) -> table

names[!(names %in% table$nbhd_name)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, nbhd_name = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., nbhd_name) -> table

  
month6%>%
  group_by(nbhd_name)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(nbhd_name, mean, count, sum) -> table1

names[!(names %in% table1$nbhd_name)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, nbhd_name = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., nbhd_name) -> table1
  
#make summary tables
  flextable(table)%>%
  colformat_num(., digits = 0)%>%
  colformat_num(., digits = 0, prefix = "$", j = c(2,4)) %>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(nbhd_name = "Neighborhood", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits")%>%
    height_all(height = .4, part = "all")-> flex
  
  flextable(table1)%>%
  colformat_num(., digits = 0)%>%
  colformat_num(., digits = 0, prefix = "$", j = c(2,4)) %>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(nbhd_name = "Neighborhood", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits")%>%
    height_all(height = .4, part = "all")-> flex01

# add powerpoint slide
report%>%
  add_slide()%>%
  ph_with("Neighborhood Summary", 
               location = ph_location_type(
                 type = "title"))%>%
  phl_with_flextable(olay = offlayout01, 2, flex)%>%
  phl_with_flextable(olay = offlayout01, 4, flex01) -> report

#add core neighborhood slide
report%>%
  add_slide(layout = "Title Slide", master = "Office Theme")%>%
  ph_with(value = "Core Neighborhoods", location = ph_location_type(type = "ctrTitle"))  -> report
```

#Individual Neighborhood Summaries

```{r}
#create comments to use to filter and name outputs
comment(cwe_tiles) <- "38"
comment(fpse_tiles) <- "39"
comment(sdb_tiles) <- "46"
comment(dbp_tiles) <- "47"
comment(we_tiles) <- "48"
comment(vp_tiles) <- "49"
comment(ac_tiles) <- "51"
comment(fp_tiles) <- "53"
comment(lp_tiles) <- "54"
comment(vd_tiles) <- "58"

for (i in list(cwe_tiles, fpse_tiles, sdb_tiles, dbp_tiles, we_tiles, vp_tiles, ac_tiles, fp_tiles, lp_tiles, vd_tiles)) {
  num <- as.numeric(comment(i))
  if(num %in% data_month$Nbrhd){
  nbhd_pres <- filter(data_month, Nbrhd == num)
  neighborhood <- unique(nbhd_pres$nbhd_name)
abbr <- unique(nbhd_pres$abbr)

#create mean, median, range stats
mean <- mean(nbhd_pres$EstProjectCost)
mean <- currency(mean, digits = 0L)
if(is.nan(mean)){mean[is.nan(mean)] <- 0}
if(is.infinite(mean)){mean[is.infinite(mean)] <- 0}
median <- median(nbhd_pres$EstProjectCost)
median <- currency(median, digits = 0L)
if(is.nan(median)){median[is.nan(median)] <- 0}
if(is.infinite(median)){median[is.infinite(median)] <- 0}
min <- min(nbhd_pres$EstProjectCost)
min <- currency(min, digits = 0L)
if(is.nan(min)){min[is.nan(min)] <- 0}
if(is.infinite(min)){min[is.infinite(min)] <- 0}
max <- max(nbhd_pres$EstProjectCost)
max <- currency(max, digits = 0L)
if(is.nan(max)){max[is.nan(max)] <- 0}
if(is.infinite(max)){max[is.infinite(max)] <- 0}

#create bullet points
summary <- block_list(
  fpar(ftext(paste(params$month, params$year, "Neighborhood Cost Breakdown", sep = " "), reg24)),
  fpar(ftext(paste("Mean:", mean, sep = " "), reg24)),
  fpar(ftext(paste("Median:", median, sep = " "), reg24)),
  fpar(ftext(paste("Range:", min, "-", max, sep = " "), reg24))
)

#create powerpoint slide
report%>%
add_slide(layout = "Two Content")%>%
  ph_with(external_img(here::here("data", "neighborhood_pics", paste(abbr, ".png", sep = "")), height = 3.73, width = 4.19), location = ph_location_left(), use_loc_size = FALSE)%>%
 ph_with(summary, location = ph_location_right(), is_list = TRUE, level_list = c(1, 2, 2, 2))%>%
  ph_with(paste(neighborhood), 
               location = ph_location_type(
                 type = "title") )-> report
 
 #Summary stats
nbhd_past <- filter(lastmonth, nbhd_name == neighborhood)
tot_pres <- filter(ytd, nbhd_name == neighborhood)
tot_past <- filter(lastytd, nbhd_name == neighborhood)

#create cost and year to date variables for each year
bp_pres <- nrow(nbhd_pres)
bp_past <- nrow(nbhd_past)
cost_pres <- mean(nbhd_pres$EstProjectCost)
cost_pres <- currency(cost_pres, digits = 0L)
if(is.nan(cost_pres)){cost_pres[is.nan(cost_pres)] <- 0}
cost_past <- mean(nbhd_past$EstProjectCost)
cost_past <- currency(cost_past, digits = 0L)
if(is.nan(cost_past)){cost_past[is.nan(cost_past)] <- 0}
bptot_pres <- nrow(tot_pres)
bptot_past <- nrow(tot_past)
totcost_pres <- mean(tot_pres$EstProjectCost)
totcost_pres <- currency(totcost_pres, digits = 0L)
if(is.nan(totcost_pres)){totcost_pres[is.nan(totcost_pres)] <- 0}
totcost_past <- mean(tot_past$EstProjectCost)
totcost_past <- currency(totcost_past, digits = 0L)
if(is.nan(totcost_past)){totcost_past[is.nan(totcost_past)] <- 0}

#create percent change variables
pct_chg_cnt <- (bp_pres - bp_past)/bp_past
pct_chg_cnt <- percent(pct_chg_cnt)
if(is.nan(pct_chg_cnt)){pct_chg_cnt[is.nan(pct_chg_cnt)] <- 0}
if(is.infinite(pct_chg_cnt)){pct_chg_cnt[is.infinite(pct_chg_cnt)] <- "Infinite"}
pct_chg_cost <- (cost_pres - cost_past)/cost_past
pct_chg_cost <- percent(pct_chg_cost)
if(is.nan(pct_chg_cost)){pct_chg_cost[is.nan(pct_chg_cost)] <- 0}
if(is.infinite(pct_chg_cost)){pct_chg_cost[is.infinite(pct_chg_cost)] <- "Infinite"}
pct_chg_ytd <- (bptot_pres - bptot_past)/bptot_past
pct_chg_ytd <- percent(pct_chg_ytd)
if(is.nan(pct_chg_ytd)){pct_chg_ytd[is.nan(pct_chg_ytd)] <- 0}
if(is.infinite(pct_chg_ytd)){pct_chg_ytd[is.infinite(pct_chg_ytd)] <- "Infinite"}
pct_chg_cost_pres <- (totcost_pres - totcost_past)/totcost_past
pct_chg_cost_pres <- percent(pct_chg_cost_pres)
if(is.nan(pct_chg_cost_pres)){pct_chg_cost_pres[is.nan(pct_chg_cost_pres)] <- 0}
if(is.infinite(pct_chg_cost_pres)){pct_chg_cost_pres[is.infinite(pct_chg_cost_pres)] <- "Infinite"}
  
#create sprints for powerpoint output  
sprint_1 <- sprintf("%s building permits in %s %s",
                    bp_pres, params$month, params$year)
sprint_2 <- sprintf("%s total building permits in %s", 
                    bptot_pres, params$year)

# text formatting
color24a <- fp_text(color = ifelse(pct_chg_cnt == 0, "#00B0F0", ifelse(pct_chg_cnt > 0, "#00B050", "red")), font.size = 24)
color20a <- fp_text(color = ifelse(pct_chg_cost == 0, "#00B0F0", ifelse(pct_chg_cost > 0, "#00B050", "red")), font.size = 20)
color24b <- fp_text(color = ifelse(pct_chg_ytd == 0, '#00B0F0', ifelse(pct_chg_ytd > 0, '#00B050', 'red')), font.size = 24)
color20b <- fp_text(color = ifelse(pct_chg_cost_pres == 0, "#00B0F0", ifelse(pct_chg_cost_pres > 0, "#00B050", "red")), font.size = 20)
  

# create summary notes
summary <- block_list(
  fpar(ftext(sprint_1, boldline)),
  fpar(ftext(paste(pct_chg_cnt, "change ", sep = " "), color24a),
       ftext(paste("compared to ", params$month, " ", (params$year -1), " (", bp_past, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(cost_pres), bold),
       ftext(paste(": Average building permit cost in", params$month, params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost, "change", sep = " "), color20a),
       ftext(paste(" compared to ", params$month, " ", (params$year -1), " (", cost_past, ")", sep = ""), reg20)),
  fpar(ftext(sprint_2, boldline)),
  fpar(ftext(paste(pct_chg_ytd, "change ", sep = " "), color24b),
       ftext(paste("YTD compared to this time in ", (params$year -1), " (", bptot_past, " total building permits)", sep = ""), reg24)),
  fpar(ftext(paste(totcost_pres), bold),
       ftext(paste(": YTD average building permit cost in", params$year, sep = " "), reg24)),
  fpar(ftext(paste(pct_chg_cost_pres, "change", sep = " "), color20b),
       ftext(paste(" YTD compared to this time in ", (params$year -1), " (", totcost_past, ")", sep = ""), reg20))
)

# write summary notes to powerpoint slide
report%>%
  add_slide(layout = 'Title and Content', master = 'Office Theme')%>%
  ph_with(value = paste(neighborhood, ": Summary Notes", sep = ""), location = ph_location_type(type = "title"))%>%
  ph_with(summary, location = ph_location_type(type = "body"), is_list = TRUE, level_list = c(1, 2, 2, 3, 1, 2, 2, 3)) -> report

#Create color palette for mapping
col <- character(0)
if("Commercial" %in% nbhd_pres$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% nbhd_pres$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Residential" %in% nbhd_pres$new_use){col <- c(col, "Residential" = "#377eb8")}

#write shapefile
shp <- filter(merge, nbhd_name == neighborhood)
st_write(shp, here::here("data", params$year, params$month, "shapefiles", paste(abbr, ".shp", sep = "")), delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, params$month, "shapefiles", paste(abbr, ".shp", sep = "")),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> nbhd_shp

#mapping
tm_shape(i) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == num) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  nbhd_shp%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> map

#save map as .jpeg
tmap_save(map, file = here::here("results", params$year, params$month, paste(abbr), paste(abbr, "_use.jpeg", sep = "")), width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, paste(abbr), paste(abbr, "_use.jpeg", sep = "")), width = 9, height = 5), location = ph_location_type(type = "body"), use_loc_size = FALSE)%>%
  ph_with(paste(neighborhood), 
               location = ph_location_type(
                 type = "title") )-> report

#create summary tables for current month and past 6 months
nbhd_pres%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table

use[!(use %in% table$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table) -> table

if(test == FALSE) {
  add_row(table, new_use = missing_category) -> table
}
table%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use) -> table

  
month6%>%
  filter(nbhd_name == neighborhood)%>%
  group_by(new_use)%>%
  summarize(mean = mean(EstProjectCost), count = n(), sum = sum(EstProjectCost))%>%
  dplyr::select(new_use, mean, count, sum) -> table1

use[!(use %in% table1$new_use)] -> missing_category
is_empty(missing_category) -> test

as.data.frame(table1) -> table1

if(test == FALSE) {
  add_row(table1, new_use = missing_category) -> table1
}
table1%>%
  replace(., is.na(.), 0)%>%
  arrange(., new_use)  -> table1

#make summary tables
  flextable(table)%>%
  colformat_num(., digits = 0)%>%
  colformat_num(., digits = 0, prefix = "$", j = c(2,4)) %>%
  autofit()%>%
  add_header_lines(values = paste(params$month, params$year, sep = " "))%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits")%>%
    height_all(height = .5, part = "all")-> flex
  
  flextable(table1)%>%
  colformat_num(., digits = 0)%>%
  colformat_num(., digits = 0, prefix = "$", j = c(2,4)) %>%
  autofit()%>%
  add_header_lines(values = "Last 6 Months")%>%
  set_header_labels(new_use = "Permit Use", 
    mean = "Average Cost", count = "# of Permits", sum = "Total Value of Permits")%>%
    height_all(height = .5, part = "all") -> flex01

# add powerpoint slide
report%>%
  add_slide(layout = "Two Content")%>%
  ph_with(flex, location = ph_location_left())%>%
  ph_with(flex01, location = ph_location_right())%>%
  ph_with("Neighborhood Summary", 
               location = ph_location_type(
                 type = "title")) -> report

if(nrow(nbhd_pres) < 15){
    
    #create in depth summary table
  nbhd_pres%>%
    dplyr::select(OwnerName, new_use, EstProjectCost, OrigAddress) -> table
  
#make a currency value
table$EstProjectCost <- currency(table$EstProjectCost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  colformat_num(., digits = 0, prefix = "$", j = 3) %>%
  autofit()%>%
  set_header_labels(OwnerName = "Owner", new_use = "New Use", 
    EstProjectCost = "Cost", OrigAddress = "address")%>%
    set_caption(paste(neighborhood, "Individual Permit Breakdown"))%>%
    height_all(height = .25, part = "all")-> flex02
  
#add powerpoint slide
  report%>%
    add_slide()%>%
    ph_with(value = paste(neighborhood, "Individual Permit Breakdown"), location = ph_location_type(type = "title"))%>%
    ph_with(flex02, location = ph_location_type(type = "body")) -> report
}

ggplot(nbhd_pres, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> plot

ggsave(here::here("results",  params$year, params$month, abbr, paste(abbr, "_cost.png", sep = "")), 
       plot = plot, width = 9, height = 5, units = "in")

#add to powerpoint report
report%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, params$month, abbr, paste(abbr, "_cost.png", sep = "")),
                       width = 9, height = 5), location = ph_location_type(type = "body"),
                       use_loc_size = FALSE)%>%
  ph_with(value = paste(neighborhood, "Permit Cost Breakdown"), 
          location = ph_location_type(type = "title")) -> report

if(num ==39){
  #add expanded service area slide
report%>%
  add_slide(layout = "Title Slide", master = "Office Theme")%>%
  ph_with(value = "Expanded Service Area", location = ph_location_type(type = "ctrTitle"))  -> report
}
  }}

  # additional notes slide
report%>%
  add_slide()%>%
  ph_with(value = "Additional Notes", location = ph_location_type(type = "title"))%>%
  ph_with(c("Data retreived from https://www.stlouis-mo.gov/data/", "Building permits with a cost of $0 were dropped", "Building permits that were cancelled were dropped", "Infinite change indicates 0 permits in the current or previous time period/comparison month so there was a overall increase or decrease"), location = ph_location_type(type = "body")) -> report

# save powerpoint report
print(report, target = here::here("results", "presentations",  params$year, params$month, paste("bldgprmt_report", params$month, params$year, ".pptx", sep = "")))

#delete any existing permit report file
mydir <- paste("/Users/loganbogenut/Documents/GitHub/stl-building-permits/results/presentations/", params$year, "/", params$month, sep = "")
file.remove(file.path(mydir, dir(path = mydir, pattern = ".pdf")))

#convert & save powerpoint as PDF
convert_to_pdf(path = here::here("results", "presentations", params$year, params$month, paste("bldgprmt_report", params$month, params$year, ".pptx", sep = "")),
               pdf_file = sub("[.]pptx", ".pdf", paste("/Users/jesstevens/Documents/Github/WUMCRC/Projects/stl-building-permits/results/presentations/", params$year, "/", params$month, "/bldgprmt_report", params$month, params$year, ".pptx", sep = "")))

#Copy PDF to Shiny App
#delete any existing permit report file in the Shiny App
#shinydr <- "/Users/loganbogenut/Documents/GitHub/crime_interactive/crime_interactive/www/"
#file.remove(file.path(shinydr, dir(path = shinydr, pattern = "bldgprmt_report")))

#file.copy(from=paste(mydir, "/bldgprmt_report", params$month, params$year, ".pdf", sep = ""), to=shinydr, 
#          overwrite = TRUE, 
#          copy.mode = TRUE)

# This code cleans our Global Environment and gives you a nice lil' message
rm(list = ls())
print("NICE JOB! You successfully ran all your code. Have an awesome day :)")
```