---
title: "Yearly Report"
author: "Logan Williams"
date: "4/22/2020"
output: html_document
params: 
  year: 2019
---

```{r}
#load dependencies
library(ggplot2)      # plot making
library(flextable)    # pretty tables
library(here)         # file path management
library(dplyr)        # data cleaning
library(officer)      # powerpoint output
library(formattable)  # currency values
library(ggrepel)      # ggplot labels
library(readr)        # load csv

#spatial packages
library(sf)           # spatial data tools
library(tmap)         # map layouts
library(tmaptools)    # tools for handeling spatial
```

```{r}
#load data
df <- read_csv(here::here("data", params$year, "summary", "clean_year.csv"))
yr5 <- read_csv(here::here("data", params$year, "summary", "5year.csv"))

# load basemap tiles
load(file = here::here("data", "basemap_tiles", "mapbox-tiles.rda"))
load(file = here::here("data", "basemap_tiles", "boundaries.rda"))
load(file = here::here("data", "basemap_tiles", "nbhd-boundaries.rda"))

# create dataframe of means
df %>%
  group_by(nbhd_name, new_use) %>%
  summarise(mean = mean(EstProjectCost), count1 = mean(count), high_cost = sum(big_cost, na.rm = TRUE), low_cost = sum(lil_cost, na.rm = TRUE)) -> means

# create powerpoint
report1 <- read_pptx()
```

```{r, include=FALSE}
#import parcel data
st_read(here::here("/data/working-db/parcels", "prcl.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> prcl

#merge by handle
merge <- df%>%
  merge(prcl, by = "HANDLE")
```

```{r}
#create custom color palette for plots
cols <- c("Industrial" = "#e41a1c", "Residential" = "#377eb8", "Commercial" = "#4daf4a", "Institutional" = "#984ea3")
```

```{r}
#title slide
report1%>%
  add_slide(layout = "Title Slide", master = "Office Theme")%>%
  ph_with(value = "St. Louis Central Corridor West Building Permits Yearly Report", location = ph_location_type(type = "ctrTitle"))%>%
  ph_with(c(params$year), location = ph_location_type(type = "subTitle"))%>%
  ph_with(value = "Washington University Medical Center", 
          location = ph_location_type(type = "dt"))%>%

 #introduction slide
  add_slide()%>%
  ph_with(value = "Introduction", location = ph_location_type(type = "title"))%>%
  ph_with(c("Data retreived from https://www.stlouis-mo.gov/data/", "Building permits with a cost of $0 were dropped", "Building permits that were cancelled were dropped"), location = ph_location_type(type = "body")) -> report1
```


# 5 Year Analysis

```{r}
yr5%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  theme(axis.title.x = element_blank()) +
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "5yr_plot.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "5yr_plot.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
```


# All Neighborhoods

```{r}
# Average cost by neighborhood for each `new_use`

ggplot(means, aes(x = nbhd_name, y = mean, fill = new_use)) +
  geom_bar(position = "dodge", stat="identity") +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  theme(axis.title.y = element_blank(), 
        axis.title.x = element_blank()) +
  labs(fill = "New Use") +
  scale_y_continuous(labels = scales::dollar_format())+
  coord_flip()

# save plot
ggsave(here::here("results", params$year, "summary", "yr_plot.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "yr_plot.png"), 
                       width = 7, height = 4), location = ph_location_type())%>%
  ph_with("Neighborhood Summary: Average Building Permit Cost", 
               location = ph_location_type(
                 type = "title") )-> report1
```

```{r}
# plot high cost permits
ggplot(df, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> plot

ggsave(here::here("results",  params$year, "summary",  "yr_cost.png"), plot = plot, dpi = 300)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "yr_cost.png"), 
                       width = 6.15, height = 5.75), location = ph_location_type(), 
                       use_loc_size = FALSE)%>%
  ph_with("Neighborhood Summary: Average Building Permit Cost", 
               location = ph_location_type(
                 type = "title"))-> report1
```

```{r}
    #create in depth summary table
  df%>%
  group_by(nbhd_name)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(nbhd_name, mean, count) -> table
  
#make a currency value
table$mean <- currency(table$mean, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(nbhd_name = "Neighborhood", 
    mean = "Average Cost", count = "# of Permits") -> flex01
  
  #add powerpoint slide
  report1%>%
    add_slide()%>%
    ph_with(value = "Neighborhood Summary", location = ph_location_type(type = "title"))%>%
    ph_with(flex01, location = ph_location_type(type = "body")) -> report1
```

### Forest Park Southeast

```{r}
if("Forest Park Southeast" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "Forest Park Southeast")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "fpse", "fpse5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "fpse", "fpse5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("Forest Park Southeast 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create fpse color palette
sub <- filter(df, nbhd_name == "Forest Park Southeast")
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```


```{r}
if("Forest Park Southeast" %in% df$nbhd_name){

#write shapefile
fpse_shp <- filter(merge, nbhd_name == "Forest Park Southeast")
st_write(fpse_shp, here::here("data", params$year, "summary", "shapefiles", "fpse.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "fpse.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> fpse

#mapping
tm_shape(fpse_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 39) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  fpse%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> fpse_map

#save map as .jpeg
tmap_save(fpse_map, file = here::here("results", params$year, "summary", "fpse", "fpse_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "fpse", "fpse_use.jpeg"), width = 9.24, height = 7.47), location = ph_location_type(type = "title"), use_loc_size = FALSE)%>%
  ph_with("Forest Park Southeast", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r fpse plot, echo=FALSE, message=FALSE}
if("Forest Park Southeast" %in% df$nbhd_name){
fpse <- filter(df, nbhd_name == "Forest Park Southeast")
ggplot(fpse, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> fpse_plot

ggsave(here::here("results",  params$year, "summary", "fpse", "fpse_cost.png"), plot = fpse_plot, dpi = 300)
}
```

```{r}
if("Forest Park Southeast" %in% df$nbhd_name){

    #create summary table
  df%>%
  filter(nbhd_name == "Forest Park Southeast")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("Forest Park Southeast") -> flex01
  
#add powerpoint slide
  report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "Forest Park Southeast", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "fpse",  "fpse_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1
}
```


### Central West End

```{r}
if("Central West End" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "Central West End")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "cwe", "cwe5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "cwe", "cwe5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("Central West End 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create cwe color palette
sub <- filter(df, nbhd_name == "Central West End")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r, warning=FALSE}
if("Central West End" %in% df$nbhd_name){

#write shapefile  
cwe_shp <- filter(merge, nbhd_name == "Central West End")
st_write(cwe_shp, here::here("data", params$year, "summary", "shapefiles", "cwe.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "cwe.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> cwe

#map shapefile
tm_shape(cwe_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 38) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  cwe%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> cwe_map

#save map as .jpeg
tmap_save(cwe_map, file = here::here("results", params$year, "summary", "cwe", "cwe_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "cwe", "cwe_use.jpeg"), width = 9.5, height = 7.5), location = ph_location_type(type="title"), use_loc_size = FALSE)%>%
  ph_with("Central West End", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r CWE plot, echo=FALSE, message=FALSE}
if("Central West End" %in% df$nbhd_name){
cwe <- filter(df, nbhd_name == "Central West End")
ggplot(cwe, aes(lrgcost, fill = new_use)) +
  geom_bar(position = "dodge", stat="count") +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> cwe_plot

ggsave(here::here("results",  params$year, "summary", "cwe", "cwe_cost.png"), plot = cwe_plot, dpi = 300)
}
```

```{r}
if("Central West End" %in% df$nbhd_name){
  
  #create summary table
  df%>%
  filter(nbhd_name == "Central West End")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("Central West End") -> flex01
  
# add powerpoint slide
report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "Central West End", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "cwe", "cwe_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1
}
```

### DeBaliviere Place

```{r}
if("DeBaliviere Place" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "DeBaliviere Place")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "dbplace", "dbplace5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "dbplace", "dbplace5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("DeBaliviere Place 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create dbplace color palette
sub <- filter(df, nbhd_name == "DeBaliviere Place")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r}
if("DeBaliviere Place" %in% df$nbhd_name){

#write shapefile  
dbplace_shp <- filter(merge, nbhd_name == "DeBaliviere Place")
st_write(dbplace_shp, here::here("data", params$year, "summary", "shapefiles", "dbplace.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "dbplace.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> dbplace

#map shapefile
tm_shape(dbp_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 47) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  dbplace%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> dbplace_map

#save map as .jpeg
tmap_save(dbplace_map, file = here::here("results", params$year, "summary", "dbplace", "dbplace_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "dbplace", "dbplace_use.jpeg"), width = 6.97, height = 7.5), location = ph_location_type(type = "title"), use_loc_size = FALSE)%>%
  ph_with("DeBaliviere Place", 
               location = ph_location_type(
                 type = "title") )-> report1
} 
```

```{r dbplace plot, echo=FALSE, message=FALSE}
if("DeBaliviere Place" %in% df$nbhd_name){
dbplace <- filter(df, nbhd_name == "DeBaliviere Place")
ggplot(dbplace, aes(lrgcost, fill = new_use)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) + 
  geom_bar(position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> dbplace_plot

ggsave(here::here("results",  params$year, "summary", "dbplace", "dbplace_cost.png"), plot = dbplace_plot, dpi = 300)
}
```

```{r}
if("DeBaliviere Place" %in% df$nbhd_name){
    
 #create summary table
  df%>%
  filter(nbhd_name == "DeBaliviere Place")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
#print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("DeBaliviere Place") -> flex01
  
# add powerpoint slide
report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "DeBaliviere Place", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "dbplace", "dbplace_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1
}
```

### Skinker DeBaliviere

```{r}
if("Skinker DeBaliviere" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "Skinker DeBaliviere")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "skinker", "skinker5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "skinker", "skinker5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("Skinker DeBaliviere 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create skinker color palette
sub <- filter(df, nbhd_name == "Skinker DeBaliviere")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r}
if("Skinker DeBaliviere" %in% df$nbhd_name){

#write shapefile
skinker_shp <- filter(merge, nbhd_name == "Skinker DeBaliviere")
st_write(skinker_shp, here::here("data", params$year, "summary", "shapefiles", "skinkerdb.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "skinkerdb.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> skinker

#mapping
tm_shape(sdb_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 46) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  skinker%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> skinker_map

#save map as .jpeg
tmap_save(skinker_map, file = here::here("results", params$year, "summary", "skinker", "skinker_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "skinker", "skinker_use.jpeg")), location = ph_location_fullsize())%>%
  ph_with("Skinker DeBaliviere", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r skinker plot, echo=FALSE, message=FALSE}
if("Skinker DeBaliviere" %in% df$nbhd_name){
skinker <- filter(df, nbhd_name == "Skinker DeBaliviere")
ggplot(skinker, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> skinker_plot

ggsave(here::here("results",  params$year, "summary", "skinker", "skinker_cost.png"), plot = skinker_plot, dpi = 300)
}
```

```{r}
if("Skinker DeBaliviere" %in% df$nbhd_name){
    
  #create summary table
  df%>%
  filter(nbhd_name == "Skinker DeBaliviere")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
#print summary table
  knitr::kable(table,
               col.names = c("New Use", "Average Cost", "Permit Count"),
               format="markdown", caption = "Skinker DeBaliviere")
  
  #print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("Skinker DeBaliviere") -> flex01
 
# add powerpoint slide
report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "Skinker DeBaliviere", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "skinker", "skinker_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1 
}
```

### West End

```{r}
if("West End" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "West End")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "westend", "westend5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "westend", "westend5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("West End 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create West End color palette
sub <- filter(df, nbhd_name == "West End")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r, message=FALSE}
if("West End" %in% df$nbhd_name){

#write shapefile
westend_shp <- filter(merge, nbhd_name == "West End")
st_write(westend_shp, here::here("data", params$year, "summary", "shapefiles", "westend.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "westend.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> westend

#mapping
tm_shape(we_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 48) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  westend%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> westend_map

#save map as .jpeg
tmap_save(westend_map, file = here::here("results", params$year, "summary", "westend", "westend_use.jpeg"), dpi = 500) 

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "westend", "westend_use.jpeg"), width = 9.5, height = 7.5), location = ph_location_type(type = "title"), use_loc_size = FALSE)%>%
  ph_with("West End", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r westend plot, echo=FALSE, message=FALSE}
if("West End" %in% df$nbhd_name){
westend <- filter(df, nbhd_name == "West End")
ggplot(westend, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> westend_plot

ggsave(here::here("results",  params$year, "summary", "westend", "westend_cost.png"), plot = westend_plot, dpi = 300)
}
```

```{r West End summary table, echo=FALSE}
if("West End" %in% df$nbhd_name){
  
  #create summary table
  df%>%
  filter(nbhd_name == "West End")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
#print summary table
  knitr::kable(table,
               col.names = c("New Use", "Average Cost", "Permit Count"),
               format="markdown", caption = "West End")
  #print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("West End") -> flex01

#add powerpoint slide
report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "West End", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "westend", "westend_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1 
}
```


### Visitation Park: Summary Notes

```{r}
if("Visitation Park" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "Visitation Park")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "vstprk", "vstprk5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "vstprk", "vstprk5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("Visitation Park 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create Visitation Park color palette
sub <- filter(df, nbhd_name == "Visitation Park")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Visitation Park Building Permit Mapping, include = FALSE}
if("Visitation Park" %in% df$nbhd_name){
  
#write shapefile
visit_shp <- filter(merge, nbhd_name == "Visitation Park")
st_write(visit_shp, here::here("data", params$year, "summary", "shapefiles", "vstprk.shp"), 
         delete_dsn = TRUE)
  
#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "vstprk.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> vstprk

#map shapefile
tm_shape(vp_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 49) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  vstprk%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> vstprk_map

#save map as .jpeg
tmap_save(vstprk_map, file = here::here("results", params$year, "summary", "vstprk", "vstprk_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "vstprk", "vstprk_use.jpeg"), width = 5.31, height = 7.5), location = ph_location_type(type = "title"), use_loc_size = FALSE)%>%
  ph_with("Visitation Park", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r vstprk plot, echo=FALSE, message=FALSE}
if("Visitation Park" %in% df$nbhd_name){
vstprk <- filter(df, nbhd_name == "Visitation Park")
ggplot(vstprk, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> vstprk_plot

ggsave(here::here("results",  params$year, "summary", "vstprk", "vstprk_cost.png"), plot = vstprk_plot, dpi = 300)
}
```

```{r, echo = FALSE}
if("Visitation Park" %in% df$nbhd_name){
    
  #create summary table
  df%>%
  filter(nbhd_name == "Visitation Park")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
  #print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("Visitation Park") -> flex01

# add powerpoint slide
report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "Visitation Park", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "vstprk", "vstprk_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1 
}
```


### Academy: Summary Notes

```{r}
if("Academy" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "Academy")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "academy", "ac5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "academy", "ac5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("Academy 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create Academy color palette
sub <- filter(df, nbhd_name == "Academy")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Academy Building Permit Mapping, include = FALSE}
if("Academy" %in% df$nbhd_name){
  
#write shapefile  
  academy_shp <- filter(merge, nbhd_name == "Academy")
  st_write(academy_shp, here::here("data", params$year, "summary", "shapefiles", "academy.shp"), 
         delete_dsn = TRUE)


#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "academy.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> academy

#tm mapping
tm_shape(ac_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 51) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  academy%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> academy_map

#save map as .jpeg
tmap_save(academy_map, file = here::here("results", params$year, "summary", "academy", "ac_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "academy", "ac_use.jpeg"), width = 5.21, height = 7.5), location = ph_location_type(type = "title"), use_loc_size = FALSE)%>%
  ph_with("Academy", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r Academy plot, echo=FALSE, message=FALSE}
if("Academy" %in% df$nbhd_name){
academy <- filter(df, nbhd_name == "Academy")
ggplot(academy, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> ac_plot

ggsave(here::here("results",  params$year, "summary", "academy", "ac_cost.png"), plot = ac_plot, dpi = 300)
}
```

```{r Academy summary table, echo = FALSE}
if("Academy" %in% df$nbhd_name){
    
  #create summary table
  df%>%
  filter(nbhd_name == "Academy")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n())-> table
  
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
  #print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("Academy") -> flex01

# add powerpoint slide
report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "Academy", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "academy", "ac_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1 
}
```


### Fountain Park: Summary Notes

```{r}
if("Fountain Park" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "Fountain Park")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "ftnprk", "ftnprk5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "ftnprk", "ftnprk5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("Fountain Park 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create Fountain Park color palette
sub <- filter(df, nbhd_name == "Fountain Park")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Fountain Park Building Permit Mapping, include = FALSE}
if("Fountain Park" %in% df$nbhd_name){

#write shapefile
ftnprk_shp <- filter(merge, nbhd_name == "Fountain Park")
st_write(ftnprk_shp, here::here("data", params$year, "summary", "shapefiles", "ftnprk.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "ftnprk.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> ftnprk

#map shapefile
tm_shape(fp_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 53) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  ftnprk%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> ftnprk_map

#save map as .jpeg
tmap_save(ftnprk_map, file = here::here("results", params$year, "summary", "ftnprk", "ftnprk_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "ftnprk", "ftnprk_use.jpeg"), width = 4.06, height = 7.5), location = ph_location_type(type = "title"), use_loc_size = FALSE)%>%
  ph_with("Fountain Park", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r ftnprk plot, echo=FALSE, message=FALSE}
if("Fountain Park" %in% df$nbhd_name){
ftnprk <- filter(df, nbhd_name == "Fountain Park")
ggplot(ftnprk, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> ftnprk_plot

ggsave(here::here("results",  params$year, "summary", "ftnprk", "ftnprk_cost.png"), plot = ftnprk_plot, dpi = 300)
}
```

```{r Fountain Park summary table, echo = FALSE}
if("Fountain Park" %in% df$nbhd_name){
    
  #create summary table
  df%>%
  filter(nbhd_name == "Fountain Park")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
  #print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("Fountain Park") -> flex01

# add powerpoint slide
report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "Fountain Park", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "ftnprk", "ftnprk_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1 
}
```

### Lewis Place: Summary Notes

```{r}
if("Lewis Place" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "Lewis Place")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "lewis", "lewis5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "lewis", "lewis5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("Lewis Place 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create Lewis Place color palette
sub <- filter(df, nbhd_name == "Lewis Place")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r Lewis Place Building Permit Mapping, include = FALSE}

if("Lewis Place" %in% df$nbhd_name){

#write shapefile
lewis_shp <- filter(merge, nbhd_name == "Lewis Place")
st_write(lewis_shp, here::here("data", params$year, "summary", "shapefiles", "lewis.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "lewis.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> lewis

#map shapefile
tm_shape(lp_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 54) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  lewis%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> lewis_map

#save map as .jpeg
tmap_save(lewis_map, file = here::here("results", params$year, "summary", "lewis", "lewis_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "lewis", "lewis_use.jpeg"), width = 6.18, height = 7.5), location = ph_location_type(type = "title"), use_loc_size = FALSE)%>%
  ph_with("Lewis Place", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r Lewis plot, echo=FALSE, message=FALSE}
if("Lewis Place" %in% df$nbhd_name){
lewis <- filter(df, nbhd_name == "Lewis Place")
ggplot(lewis, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> lewis_plot

ggsave(here::here("results",  params$year, "summary", "lewis", "lewis_cost.png"), plot = lewis_plot, dpi = 300)
}
```

```{r, echo=FALSE}
if("Lewis Place" %in% df$nbhd_name){
    
    #create summary table
  df%>%
  filter(nbhd_name == "Lewis Place")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
  #print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("Lewis Place") -> flex01

# add powerpoint slide
report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "Lewis Place", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "lewis", "lewis_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1 
}
```

### Vandeventer

```{r}
if("Vandeventer" %in% df$nbhd_name){
year <- filter(yr5, nbhd_name == "Vandeventer")
year%>%
  group_by(yr)%>%
  summarize(mean = mean(EstProjectCost), count = n())%>%
  select(yr, mean, count) -> yr

yr$mean <- currency(yr$mean, digits = 0L)

ggplot(data = yr, aes(x = yr, y = count))+
  geom_point()+
  geom_line()+
  theme(
    axis.title.x = element_blank())+
  geom_label_repel(aes(label = mean),
                  box.padding   = 0.35, 
                  segment.color = 'grey50')+
  ylab("Number of Building Permits")

# save plot
ggsave(here::here("results", params$year, "summary", "vandy", "vandy5yr.png"), width = 7, height = 4, units = "in", dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "vandy", "vandy5yr.png"), width = 7, height = 4),
          location = ph_location_type())%>%
  ph_with("Vandeventer 5 Year Analysis", 
               location = ph_location_type(
                 type = "title") )-> report1
}
```

```{r}
#create Vandeventer color palette
sub <- filter(df, nbhd_name == "Vandeventer")
#create empty character vector that will become the color palette
col <- character(0)
if("Commercial" %in% sub$new_use){col <- c("Commercial" = "#4daf4a")}
if("Industrial" %in% sub$new_use){col <- c(col, "Industrial" = "#e41a1c")}
if("Institutional" %in% sub$new_use){col <- c(col, "Institutional" = "#984ea3")}
if("Residential" %in% sub$new_use){col <- c(col, "Residential" = "#377eb8")}
```

```{r}
#write shapefile
vandy_shp <- filter(merge, nbhd_name == "Vandeventer")
st_write(vandy_shp, here::here("data", params$year, "summary", "shapefiles", "vandy.shp"), 
         delete_dsn = TRUE)

#Load shapefile
st_read(here::here("data", params$year, "summary", "shapefiles", "vandy.shp"),
        stringsAsFactors = FALSE) %>%
  st_transform(crs = 32615) -> vandy

#mapping
tm_shape(vd_tiles) +
  tm_rgb() +
  nhoods_sf %>%
  filter(., neighborhood == 58) %>%
  tm_shape() +
    tm_fill(col = "#9ecae1",
            alpha = .5) +
    tm_borders(col = "black",
               lwd = 2,
               lty = "dashed") +
  vandy%>%
  tm_shape() +
    tm_bubbles(size = .25,
               col = "new_use",
               palette = col,
               title.col = "Building Permit Type") +
  tm_credits("© Mapbox, © OpenStreetMap", position = c("left", "BOTTOM")) +
  tm_layout(
    frame = FALSE,
    legend.bg.color = "white",
    legend.frame=TRUE,
    legend.outside = TRUE,
    legend.position = c("right", "bottom")) -> vandy_map

#save map as .jpeg
tmap_save(vandy_map, file = here::here("results", params$year, "summary", "vandy", "vandy_use.jpeg"), dpi = 500)

#add to powerpoint report
report1%>%
  add_slide()%>%
  ph_with(external_img(here::here("results", params$year, "summary", "vandy", "vandy_use.jpeg"), width = 8.27, height = 7.5), location = ph_location_type(type = "title"), use_loc_size = FALSE)%>%
  ph_with("Vandeventer", 
               location = ph_location_type(
                 type = "title") )-> report1
```

```{r vandy plot, echo=FALSE, message=FALSE}
if("Vandeventer" %in% df$nbhd_name){
vandy <- filter(df, nbhd_name == "Vandeventer")
ggplot(vandy, aes(lrgcost)) +
  scale_colour_manual(
    values = cols,
    aesthetics = c("colour", "fill")
  ) +
  geom_bar(aes(fill = new_use), position = "dodge", stat="count") +
  theme(
    plot.title = element_text(hjust = 0.5),
  )+
  ylab("Number of Permits") +
  xlab("Building Permit Cost") +
  labs(fill = "New Use") -> vandy_plot

ggsave(here::here("results",  params$year, "summary", "vandy", "vandy_cost.png"), plot = vandy_plot, dpi = 300)
}
```

```{r}
  #create summary table
  df%>%
  filter(nbhd_name == "Vandeventer")%>%
  group_by(new_use)%>%
  summarize(avg_cost = mean(EstProjectCost),
            permit_count = n()) -> table
  
#make avg_cost a currency value
table$avg_cost <- currency(table$avg_cost, digits = 0L)
  
  #print summary table
  flextable(table)%>%
  autofit()%>%
  set_header_labels(new_use = "New Use", 
    avg_cost = "Average Cost", permit_count = "# of Permits")%>%
    set_caption("Vandeventer") -> flex01

#add powerpoint slide
  report1%>%
    add_slide(layout = "Two Content")%>%
    ph_with(value = "Vandeventer", location = ph_location_type(type = "title"))%>%
    ph_with(external_img(here::here("results", params$year, "summary", "vandy", "vandy_cost.png"), width = 5.45, height = 5.45), ph_location_left(), use_loc_size = FALSE)%>%
    ph_with(flex01, location = ph_location_right()) -> report1
```

```{r}
#save powerpoint output
print(report1, target = here::here("results", params$year, "summary", "finalreport.pptx"))
```
